name: PHP CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    name: PHP Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: ['8.3']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: ./.github/actions/libextism
      - name: Setup PHP env
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ffi
          tools: composer
        env:
          fail-fast: true
      - name: Test PHP SDK
        run: |
          make test